
services:
  nginx:
    container_name: app_nginx
    restart: always
    image: nginx:latest
    ports:
    - ${PORT}:80
    volumes:
    - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template
    - ./entrypoint.sh:/docker-entrypoint.d/entrypoint.sh
    entrypoint: ["/docker-entrypoint.d/entrypoint.sh"]
    env_file:
      - ./.env
    depends_on:
      - blue
      - green
    networks:
    - net

  blue:
    container_name: app_blue
    restart: on-failure
    image: ${BLUE_IMAGE}
    ports:
    - 8081:${PORT}
    env_file:
      - ./.env
    environment:
    - APP_POOL=blue
    - RELEASE_ID=${RELEASE_ID_BLUE}
    networks:
    - net

  green:
    container_name: app_green
    restart: on-failure
    image: ${GREEN_IMAGE}
    ports:
    - 8082:${PORT}
    env_file:
      - ./.env
    environment:
    - APP_POOL=green
    - RELEASE_ID=${RELEASE_ID_GREEN}
    networks:
    - net
  
networks:
  net:
    driver: bridge



  




